apiVersion: v1
kind: Secret
metadata:
  name: gecko-secrets
  namespace: default
stringData:
  FOO: ENC[AES256_GCM,data:d6cv,iv:Lznq6MalI6ipDs9YMueLu4tjkWveGOgEbXqLp2DTJfM=,tag:XOpHZMrMX+PE0OWLjyCN/Q==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KGo/BupoJx1pBF/FCC6xRhX3dOE=,iv:Vj2U054bGNOHrxdRwg6YV027FSSuQV8YXtbaK8XmnDA=,tag:eQyz+4Wfy8gGMIHrGvma2w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JGuMsSlWFIzMlx4MKJuiu0GmHo9AOPL6/aVd744AKZySjU/lh7wXBg==,iv:5lAVYXK3SBBBB6yid+DIRhvORsFmnq1jck6KdffR5+4=,tag:qYKcYo8v3htdCFNbTUBCmg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2022-03-29T19:48:06Z"
  mac: ENC[AES256_GCM,data:ZFLKBvHTTrd5T01ntUvQvPTDkwGBqrIgjnNUQ/JQaCq/JoVlL1uAKpoL/IfmfBpWF2ywgiazde3mfqCDceOGiOLQzyLY2BM/3V2fjdkuy3MSzdOwxTDeY8dq3bzmRU4a0hbeVnDQ8MF3Ven2fGhvma07YS2OcoDnw5ZoLfb3OGI=,iv:+rjAExkOIKDOWwFbAPS37hjhnJ39dwXUV/4/bWvQZHM=,tag:RCo6DOFRyiyjMabt0qsw1g==,type:str]
  pgp:
    - created_at: "2022-03-29T19:48:04Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA6Q9JKCuGwb9AQ//Y0wE/Mu8P7mQcb5T8QJQz+5lvYxw3tQ2G3M91wSWoI+H
        2V1glBtywBH5oAcZ2QRlB1YMAd/xIcAlzY0EmSutY/EoWKNqCx1IMqwuIDEgPJ+s
        xAbKcLSAKwoz4OKxJeFAQZPlFQb/M2DO3J1uGE2POrjtGdA9GaAB/jWNVJlmTOJz
        F0wIOlvg3GKX6Nab6YFvrnh8tpkPh27lIz5rJVshjXRMfUFhIbrvoZH0v8dY5dLP
        ZueoTT37JPBdsljXJxLdgIERytzjYthuWGvqp/5Doke6mWfAZ1o8yTam0Om7lEVY
        WkOvpIJRZIRWWwLklN6lrUxSlhEYRU6Sms4DAJUIHj/tfSY0aYaYNalLPvV1fVV/
        XbPOPsL3gZaQQ8tEQeekZ+72NLKAOoHnCcT9/BTtJ2BefJwyITAUiCrCtknmvfZI
        74bDAn/6+CSrWoy+2F0x6QN9lHVM/SI1rMJJJsomWF7bj7GHBcokv8ULmjUU+T0S
        JafGhMJriFs668Yz4KBV1jRXElsiifoULGDpcNjdIJHGw3LHzHyq6ijL4VhmhbGk
        WZQas4fWJSsrPAONOjmGIQq+NPVQ6PeccfAJc0sN5TTi21HHsJx8I50LLx+aRg3a
        ZlDHe+ogrLt7kijqozXTEU6syDjX58vpiZuHsZXtT8KHx7l8yXL0hSVUUQud2DHU
        aAEJAhDDtPQ5JHEI4HI05pTfdfstt17ckAIc3O5GrkAGOMzPZ2qJQEiey1BuD6VJ
        /hdqPA29pJSVNd+PEIqO9bUjUMaVOF+EfNJRCatOibgo+qrGiaJKwHA6a0mlBQlm
        m6GgXqu5XaMV
        =vpbM
        -----END PGP MESSAGE-----
      fp: B16AEAB002B6063D1C694581BB699D5B9C1CDA63
  encrypted_regex: ^(data|stringData)$
  version: 3.7.2
