apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: hello-html
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hello-html
  policy:
    semver:
      range: ^0.x-0