version: '3.8'

services:
  traefik:
    image: traefik:v2.2
    command: --providers.docker --entrypoints.web.address=:8080 --providers.docker.exposedbydefault=false
    depends_on:
      - gecko
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - .:/data
  gecko:
    volumes:
      - .:/app
      - .:/data
    depends_on:
      - redis
    expose:
      - "8080"
    # ports:
    #   - "8080:8080"
    image: acim/go-reflex
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gecko.rule=PathPrefix(`/gecko`)"
      - "traefik.http.routers.gecko.service=gecko"
      - "traefik.http.services.gecko.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.gecko.stripprefix.prefixes=/gecko"
      - "traefik.http.middlewares.gecko.stripprefix.forceslash=false"
      - "traefik.http.routers.gecko.middlewares=gecko"
    environment:
      RACE_DETECTOR: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      FOO: ${FOO}