name: auth
on:
  push:
    branches:
      - main
    paths:
      - services/auth/**
      - .github/workflows/auth.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        run: echo "::set-output name=tags::ghcr.io/facutk/auth:latest,ghcr.io/facutk/auth:0.0.$(date +'%Y%m%d%H%m%S')-$(git rev-parse --short HEAD)"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./services/auth
          file: services/auth/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
