name: hello-html
on:
  push:
    branches:
      - main
    paths:
      - services/hello-html/**
      - .github/workflows/hello-html.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        run: |
          cd services/hello-html
          docker build . --tag ghcr.io/${{ github.actor }}/hello-world:latest
          docker push ghcr.io/${{ github.actor }}/hello-html:latest
          docker push ghcr.io/${{ github.actor }}/hello-html::0.0.$(date +'%Y%m%d%H%m%S')-$(git rev-parse --short HEAD)
