name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: pseudoversion
        run: echo "::set-output name=pseudoversion::0.0.$(date +'%Y%m%d%H%m%S')-$(git rev-parse --short HEAD)"
      - id: meta
        run: echo "::set-output name=tags::${{ github.repository }}:latest,${{ github.repository }}:${{ steps.pseudoversion.outputs.pseudoversion }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
